Develop/#7
jojojo0501/tenkue-hotel-r018 pull request #12
Opened 2021-02-06 10:13 UTC by jojojo0501

トップページのレビューをお願いします。

2021-02-09 15:35 UTC, nitro583 requested changes
レイアウト確認いたしました。
気になる点いくつかコメントを残していますのでご確認お願いします。

FLOCCS記法のscss記述方法は参考になりました。&__containerと重ねて
書いていくことができるというのを理解しました。（Qiitaの記事にもありましたね・・・）

2021-02-09 15:35 UTC, nitro583 commented on src/asset/sass/object/project/_top.scss
> +  margin-top: 7%;
### 必須
margin-top はヘッダーの高さに合わせておかないと、統合したときに
ヘッダーと画像の間に隙間ができてしまうと思いますので、”7%”ではなく
”80px”で統一したほうが良いと思います。

2021-02-09 15:35 UTC, nitro583 commented on src/asset/sass/object/project/_top.scss
> +  margin-bottom: 15%;
※任意です
こちらはヘッダーとは異なり、見栄えが大きく変わることはないと思いますので
ほとんど問題ないと思いますが、15%は開きすぎだと思うので調整の余地ありと思います。

見本は60pxほど余白をpaddingで確保しているようです。

2021-02-09 15:35 UTC, nitro583 commented on src/asset/sass/object/project/_top.scss
> +  //-------------エリアガイドー-------------------------------//
### 必須
p-top__container で括っていますが、
見本のエリアガイドの部分は背景色が若干異なりますので
背景色の指定をお願いします。
見本は　 #fffff9;

2021-02-09 15:35 UTC, nitro583 commented on src/asset/sass/object/project/_top.scss
> +  &__title {
任意

字間が狭いので
letter-spacing 2px;を追加すると良いと思います。

2021-02-09 15:35 UTC, nitro583 commented on src/asset/sass/object/project/_top.scss
> +
### 必須

スマホ解像度のときにエリアガイド右側のサムネイル画像のレイアウトが崩れてしまいます。
レイアウト変更時に　flex-wrap: wrap;　を追加して調整すれば良さそうです。

2021-02-09 15:35 UTC, nitro583 commented on src/asset/sass/object/project/_top.scss
> +    height: 600px;
任意
heightが固定のためウインドウ高さに応じて画像サイズが変わらないのが
見本と若干異なるので余裕があれば調整しても良いかと思います。

2021-02-09 15:35 UTC, nitro583 commented on src/asset/sass/object/project/_top.scss
> +      height: 300px;
スマホ解像度も高さの解像度によって見本と結構見え方が違うので確認してみてください。

2021-02-10 13:35 UTC, nitro583 requested changes
背景色以外のところはOKと思います。
お手数をおかけしますが、ご確認お願いします。

2021-02-10 13:35 UTC, nitro583 commented on src/asset/sass/object/project/_top.scss
> +    background: #fffff9;
すみません説明がわかりづらかったですね、
「エリアガイドの部分の背景全体」が#fffff9なのですが、
ほかの項目は＃FFFです。
エリアガイドにのみ適用するように修正する必要があります。

また、ContainerはWidthが数値指定してあるので背景色を全体に適用できず、
新たにDivで親要素をつくって区切り、背景色指定する必要があるかもです。

2021-02-11 13:58 UTC, oga0927 approved these changes

2021-02-11 13:58 UTC, oga0927 commented on src/ejs/index.ejs
> +                        <h2 class="p-top__title">AREA GUIDE</h2>
max-width:576pxのフォントサイズが40pxなので32pxに変更すると見本と同じように
バランスがよくなるかと思います。

2021-02-11 13:58 UTC, oga0927 commented on src/ejs/index.ejs
> +                                <a class="p-top__button" type="button" href="/areaguide/">詳細はこちら</a>
画像とボタンが離れてしまっているのでmargin: 20px;でいいかと思います。

2021-02-12 01:58 UTC, jojojo0501 commented on src/ejs/index.ejs
> +                        <h2 class="p-top__title">AREA GUIDE</h2>
p-top__titleでしょうか？
見本は8vwで指定しているようです。
作成時、vwでの指定は慣れていなかったので、近いpx指定で記載しておりました。
32pxよりは現在の方が見本よりかと思いました。

2021-02-16 02:20 UTC, Taka-hyt commented
@jojojo0501 
3点確認お願いします。
- `package.json`と`package-lock.json`は変更ファイルに含まれていなかった認識ですが、こちらもマージする必要がありますか？変更が加えられているので。
- `src/index.ejs`、`src/asset/sass/object/project/_top.scss`、`src/asset/js/slider.js`内のインデントが揃っていないのが気になるので修正してもらえますか。現場に入ったら絶対に言われると思います。自動フォーマットのプラグインなどを使用すると良いと思います。
- メインビジュアルの画像スライダーの初期状態の挙動が気になります。最初に`mv_04.jpg`の画像が表示され、しばらく経ってから順番に`mv_01.jpg`、`mv_02.jpg`、`mv_03.jpg`と変わっています。最初に`mv_01.jpg`の画像が表示されるように変更お願いします。（JSの変更せず、CSSの調整だけでいけます）

2021-02-19 10:54 UTC, Taka-hyt commented
![LGTM](https://user-images.githubusercontent.com/53964838/108495546-44612e80-72ec-11eb-88d9-03013cdbc5cc.jpg)

2021-02-19 10:54 UTC, merged