Develop/#8
jojojo0501/tenkue-hotel-r018 pull request #13
Opened 2021-02-06 10:16 UTC by jojojo0501

ACCESSページのレビューをお願いします。

2021-02-10 14:03 UTC, nitro583 requested changes
細かいところばかりの指摘となり申し訳ありません。。
レイアウトの実装は見本とほぼ変わらず大きな問題ではないですが
余裕があれば確認してみてください。

2021-02-10 14:03 UTC, nitro583 commented on src/asset/sass/object/project/_access.scss
> +    margin:7% 0;
Toppage同様、ヘッダーサイズと合わせるために
80pxで指定したほうが良いと思います。

2021-02-10 14:03 UTC, nitro583 commented on src/asset/sass/object/project/_access.scss
> +        height: 3px;
細かいかもですが、見本は2pxになっています。
余裕があれば、、直すと完全コピーに近づきます。

2021-02-10 14:03 UTC, nitro583 commented on src/asset/sass/object/project/_access.scss
> +  letter-spacing: 2px;
見本の場合　タイトル部分はletter-spacingが適用されていますが
本文には適用されていませんので本文には適用させないクラス分けが必要かと思います。

2021-02-10 14:03 UTC, nitro583 commented on src/asset/sass/object/project/_access.scss
> +
margin-bottom: 50px;
justify-content: space-between;

画像とテキストのマージンがほとんどなかったので上記を追加し
imgのmargin-leftとmargin-bottomを削除しjustify-content: space-between;　を追記

↑このようにしたほうが、imgの左端と下に微妙なマージンが出ず、
綺麗に仕上がるかと思います。

2021-02-10 14:03 UTC, nitro583 commented on src/asset/sass/object/project/_access.scss
> +      margin-left: 1%;
margin-leftは削除

2021-02-10 14:03 UTC, nitro583 commented on src/asset/sass/object/project/_access.scss
> +      margin-bottom: 1%;
margin-bottomは削除

そのかわりに
&:nth-of-type(n+5) {
margin-top: 10px;
}

でそれらしくなるかと思います。
[参考　何番目系の便利なCSSまとめ](https://qiita.com/ituki_b/items/62a752389385de7ba4a2)

2021-02-12 02:40 UTC, oga0927 commented on src/ejs/access/index.ejs
> +                    <div class="p-access__ImageList">
画像と文字が詰まっているので、見本ではmargin-bottom: 25px;が付与されています。

2021-02-12 02:48 UTC, oga0927 commented on src/ejs/access/index.ejs
> +                    <b>【公式】TENKUE HOTEL</b><br>
見本より文字のサイズが大きくなっているため、bタグではなくh4タグでいいかと思います。
他は見本と同じで、コードの記述もわかりやすく諸々参考にさせていただきました。
特にbreakpointの使い方は初めて知りました。

2021-02-16 10:31 UTC, Taka-hyt commented
![LGTM](https://user-images.githubusercontent.com/53964838/108050896-922c2b80-708d-11eb-8ed2-4776162f776d.jpg)

2021-02-16 10:31 UTC, merged