Develop/#3
jojojo0501/tenkue-hotel-r018 pull request #14
Opened 2021-02-12 13:17 UTC by oga0927

フッターのコードレビューをお願いいたします。

2021-02-12 13:49 UTC, nitro583 requested changes
レイアウトは問題ありません。
リンク設定が#のままなので各ページへのリンクを設定してください。
画像のaltはしっかりと記入したほうが無難です。

2021-02-12 13:49 UTC, nitro583 commented on src/ejs/_includes/_footer.ejs
> +      <a href="#">©︎2020 Tenkue Hotel</a>
トップページへのリンクを設定しましょう

2021-02-12 13:49 UTC, nitro583 commented on src/ejs/_includes/_footer.ejs
> +            <a class="l-footer__nav__link" href="#">TOP</a>
各ページへのリンクを設定しましょう

2021-02-12 13:49 UTC, nitro583 commented on src/ejs/_includes/_footer.ejs
> +            <img src="../../asset/image/logo_footer.svg" alt="">
見た目に影響はないですが、altにTENKUE HOTEL
と設定すると良いと思います。

2021-02-13 02:49 UTC, jojojo0501 reviewed
footerを確認しました。
細かい指摘で恐縮ですが、お時間がありましたら、ご確認のほどよろしくお願いします。

2021-02-13 02:49 UTC, jojojo0501 commented on src/ejs/_includes/_footer.ejs
> +            <a class="l-footer__nav__link" href="/areaguide/">AREA GUIDE</a>
AREAGUIDEのAREAとGUIDEの間に半角スペースがあるため（見本にはないようです。）
下記のように1000〜576の画面幅の一部でレイアウトが崩れています。
半角スペースを取り除いたところ、見本と完全一致となりました。
https://gyazo.com/aa37d1f772878c8fce52759c31baa83a

2021-02-14 13:28 UTC, Taka-hyt commented on src/asset/sass/layout/_footer.scss
> +
ここの`<a>`タグですが、下記に記述されている`&__nav__link`と同一ではないですか？
どちらか（できればclass）にまとめて記述した方が綺麗だと思います。

2021-02-14 13:31 UTC, Taka-hyt commented on src/ejs/_includes/_footer.ejs
> +          </li>
`href`のURLの指定が`/hoge/`、`/hoge`、`hoge`などバラバラになっているので統一した方が見やすいと思いますので統一お願いします。

2021-02-18 12:27 UTC, Taka-hyt commented on src/asset/sass/layout/_footer.scss
> +    a {
@oga0927 
ここに`<a>`タグないのコードを移動させているかと思いますが、サイトの表示は確認されていますか？
表示に不具合出ています。一部不要なコードが含まれていますのでご確認ください。

2021-02-20 02:17 UTC, Taka-hyt commented
@oga0927 
`<a>`タグの箇所に関して意図が伝わってないようですが、表示はされているので良いことにします...
![LGTM](https://user-images.githubusercontent.com/53964838/108580062-37d0ea80-736d-11eb-89a6-200223d48e85.jpg)

2021-02-20 02:17 UTC, merged