Develop/#1
jojojo0501/tenkue-hotel-r018 pull request #15
Opened 2021-02-13 00:54 UTC by oga0927

見本とハンバーガーの実装は異なりますが、コードレビューをよろしくお願いいたします。

2021-02-13 13:42 UTC, nitro583 requested changes
取り急ぎハンバーガーメニューの実装部分以外で気になったところをコメントしています。
ご確認よろしくお願いします。

2021-02-13 13:42 UTC, nitro583 commented on src/asset/sass/layout/_header.scss
> +
見本だとぼかしなしのボックスシャドウで変な感じにはなっちゃっていますが、それっぽくするなら以下の記述を追加してみてください。

box-shadow: 0px 1px 2px #ddd;

2021-02-13 13:42 UTC, nitro583 commented on src/asset/sass/layout/_header.scss
> +
headerをスクロールしても固定されるようにする必要があります

position: fixed;
width: 100%;
top: 0;
left: 0;
z-index: 999;

2021-02-13 13:42 UTC, nitro583 commented on src/asset/sass/layout/_header.scss
> +    height: 25px;
ロゴの画像サイズが見本より小さくなっています。

img {
height 100%; 
width: auto;
}
 を追加してください。

2021-02-13 13:42 UTC, nitro583 commented on src/asset/sass/layout/_header.scss
> +  transition: .3s;
カーソルホバーで背景色が変わる動作を実装してください。

&:hover {
background-color: rgba(155,155,155,0.2);
}

2021-02-13 13:42 UTC, nitro583 commented on src/asset/sass/object/component/_hamburger.scss
> +    border:none;
ホバーしてもカーソルが変わらないので
cursor: pointer;
を追記するといいと思います。

2021-02-14 08:44 UTC, jojojo0501 commented
最新版を確認いたしました。特にコメント等はございません。

2021-02-20 02:29 UTC, Taka-hyt commented
@oga0927 
以下3点修正お願いします。
- ヘッダーは`position: fixed;`でスクロールしても常にサイト上部に不要時されるように修正してください。（PC/TAB/SP）
- ハンバーガーメニューを開いた際は縦スクロールできないように調整してください。（TAB/SP）
- JSでclassを制御するときは`open`ではなく`is-open`というclass名にした方が、JSで制御されているんだな、と気付きやすいと思います。

2021-02-20 13:57 UTC, merged