Develop/#2
jojojo0501/tenkue-hotel-r018 pull request #16
Opened 2021-02-13 01:26 UTC by oga0927

コードレビューをお願いいたします。

2021-02-13 03:08 UTC, jojojo0501 reviewed
AREA GUIDEレビューしました。
大きな問題ではないと思いますが、トップ画像の拡大率について記載しました。
表示には影響しないですが、コードについて、時間をかなり詰めて実装されていらっしゃったと思いますので、最終化として、不要な改行の削除、コメントの追加等をいただけるとより分かりやすくなると思いました。

2021-02-13 03:08 UTC, jojojo0501 commented on src/asset/sass/object/project/_areaguide.scss
> +      // font-size: 4vw;
不要であれば、消して良いと思います。

2021-02-13 03:08 UTC, jojojo0501 commented on src/asset/sass/object/project/_areaguide.scss
> +}
background-position: center;を指定してあげることで、拡大率が見本と同様になります。

https://developer.mozilla.org/ja/docs/Web/CSS/background-position

2021-02-13 03:09 UTC, jojojo0501 commented on src/asset/sass/object/project/_areaguide.scss
> +      // font-size: 4vw;
フォントサイズの指定についてです。

2021-02-13 14:26 UTC, nitro583 requested changes
各説明文の誤字脱字が多いので一度見本と比べてみてください。
もしデザイン・文章が決まっている案件を実装する場合はコピペしたほうが
効率も良いしミスも減らせると思います。

指摘事項に入れていませんが、余裕があれば以下の仕様実装すれば
より完成度が高まると思いますし、UXも改善されると思います。

・モーダルが開いているときはスクロールさせない
・モーダルでグレーアウトしているところをクリックしても閉じる

2021-02-13 14:26 UTC, nitro583 commented on src/ejs/areaguide/index.ejs
> +                                <p>大阪駅の中心地で、駅エリアにはノースゲートビルディング、サウスゲートビルディングに入る
おそらく手打ちで転記していると思いますので、ところどころに誤字脱字がみられます。

基本的にデザインが決まっている場合は元からコピペの方が無難だと思います。

余裕があれば見本と読み比べてみてください。

2021-02-13 14:26 UTC, nitro583 commented on src/ejs/areaguide/index.ejs
> +                                </p>
ここのpにmargin-bottomがないので、
次の【公式サイトはこちら】との行間が狭くなってしまっています。
SCSSで追記してください。

2021-02-13 14:26 UTC, nitro583 commented on src/ejs/areaguide/index.ejs
> +                                <p>イギリスの有名情報雑誌が2008年に選出した「世界の建築トップ20」にランクインした
ここも見本と文章が違います。

2021-02-13 14:26 UTC, nitro583 commented on src/ejs/areaguide/index.ejs
> +                                    <a href="https://www.jr-odekake.net/eki/top?id=0610130"
URLの記述とリンク先がスカイビルのURLになっていません

2021-02-13 14:26 UTC, nitro583 commented on src/ejs/areaguide/index.ejs
> +                                    <a href="https://www.jr-odekake.net/eki/top?id=0610130"
ここもURLの記述とリンク先が大阪城になっていません。

2021-02-13 14:26 UTC, nitro583 commented on src/ejs/areaguide/index.ejs
> +                                <p>難波から心斎橋までの一駅区間と長く続く商店街でショッピングを楽しめます。「戎橋・心斎橋商店街」
ここも見本と文章が若干ちがいます。

2021-02-13 14:26 UTC, nitro583 commented on src/ejs/areaguide/index.ejs
> +                                    <a href="https://www.jr-odekake.net/eki/top?id=0610130"
ここは見本のほうもURL記述が間違っています・・・
が、ここは心斎橋商店街のURLに修正しておくと良いかと思います。

2021-02-13 14:26 UTC, nitro583 commented on src/ejs/areaguide/index.ejs
> +                                    子どもから大人まで楽しめ、ワールドクラスのエンターテイメントに出会えるテーマパークです。
ここも文章が違います。

2021-02-13 14:26 UTC, nitro583 commented on src/ejs/areaguide/index.ejs
> +                                    >https://www.jr-odekake.net/eki/top?id=0610130</a>
USJの記述・リンク先にしましょう。

2021-02-13 14:26 UTC, nitro583 commented on src/ejs/areaguide/index.ejs
> +                                <p>吉野家は、牛丼を主力商品とする、大手外食チェーンストア。株式会社吉野家ホールディングの子会社・
ここも1文字違います。確認願います。

2021-02-13 14:26 UTC, nitro583 commented on src/ejs/areaguide/index.ejs
> +                    ぜひ大阪駅観光の計画にお役立てください</h3>
・見どころ　が漢字になっています。
・句読点が足りていません。

こういうのはコピペしましょう。

2021-02-13 14:26 UTC, nitro583 commented on src/ejs/areaguide/index.ejs
> +                            <button class="p-areaguide__detailButton js-modal-opener" data-target="modal01">詳しく見る</button>
見本と表記が違います。
×詳しく見る
○詳しくみる

2021-02-14 13:55 UTC, Taka-hyt commented
@oga0927 
レイアウトなど特に問題ないので良いですが、モーダルの実装方法が気になります。
`modal01`、`modal02`というように順番に数字が割り振られていますが、`modal01`と`modal02`の間にコンテンツを追加してほしい（例えば道頓堀など）と言われた場合どうしますか？
新しく追加したコンテンツを`modal07`としますか？この場合は`modal01`、`modal07`、`modal02`のように順番がバラバラになってしまします。
もしくは、既存の`modalXX`の記述を`modal01`、`modal02`、`modal03`と記述し直しますか？この場合、全ての`modalXX`の記述を直さないといけないので手間がかかり、変更箇所が多いとミスを誘発する可能性があります。
後々変更しやすいように実装してみると良いと思います。

2021-02-18 12:29 UTC, Taka-hyt commented
![LGTM](https://user-images.githubusercontent.com/53964838/108357136-61382c00-7230-11eb-8f20-8c31ff8daba4.jpg)

2021-02-18 12:29 UTC, merged